import configparser
import json
import os
from http.server import BaseHTTPRequestHandler, HTTPServer
import subprocess
import sys
import time
from usbmonitor import USBMonitor
import threading
import pystray
import base64
from PIL import Image
import io
import win32serviceutil

ICO_BASE = """
AAABAAMAEBAAAAEAIABoBAAANgAAACAgAAABACAAKBEAAJ4EAAAwMAAAAQAgAGgmAADGFQAAKAAAABAAAAAgAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQEAgjdXL4Q7VIyJOlY+AAAAAAAAAAAAAAEAAAEAAAEAAQAAAQAAiDpWPoU6VIyDN1cvAAAAAAEAAAAAAAAAAAEAAIQ2VVWHOVT/hThTcQAAAQAAAAAAAQAAAAEAAAABAAEAAAAAAIU4UnGGOVX/hDdVVQABAQAAAQAAAAAAAAEBAACGNlEThjZVOYY4VYeGOVXFhThUhAAAAAAAAAAAhTlVhIc5VcWGOVWHhjdVOYY3URMAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAQCGO1WNhjlU/4Y5VKoAAAAAAAAAAIY4VKqGOFT/hjpVjQEAAQABAQAAAAABAAABAAAAAQAAAAAAAII2Vy+EOlSMhjhUzIY5VP+GOFXZhDpUjIQ6VIyHOVXZhjhV/4c4VcyFOlSMgjZWLwABAQAAAQAAAQAAAAABAACEN1VVhzhV/4Y5VP+GOVX/hjlU/4Y5Vf+GOVX/hjlV/4Y4Vf+GOVX/hjlU/4Q2VFUBAAAAAAAAAAAAAAABAQAAhDZUVYY4Vf+GOFX/hjlUxoQ4VamGOVX1hjlV9YU5VKmHOFXGhjhV/4c5Vf+FNlRVAAAAAAAAAQB3Ok8NhjhVcoU5VKGGOVX/hjlU/4Q2VFUAAQAAhjlV4oY4VeIAAAEAhTZVVYY5Vf+HOVX/hTlUoYY5VXKAQFUMhjpViYY4VXKFOVWhhjlU/4Y5Vf+ENlRVAAAAAIY4VeKGOFTiAAABAIQ2VFWGOVT/hjlV/4Q5VKGHOFVyhztUiYc5VeIBAAAAhDZUVYc5Vf+GOVX/hDZUVQAAAACHOFTihjhV4gABAACEN1VVhjlU/4Y4VP+ENlRVAAAAAIY5VOKGOFXiAAAAAIU2VVWGOVX/hjlV/4Y4VNmGOVTFhjlV+IY5VfiGOVXFhjhV2YY5VP+GOVT/hDZUVQAAAACHOVTihjhV4gEAAACCNlcvhjhVv4Y4Vf+HOFX/hjlU/4Y5Vf+GOVX/hjlV/4Y5VP+GOVX/hjlUv4I2Vi8AAAAAhjhV4oY5VeIAAQAAAAAAAII2VTOGOVXAhjhV/4Y5Vf+GOFT/hjlV/4c5VP+GOVT/hjhVwII2VTMAAAAAAAEAAIY4VeKGOFVMAQAAAAEAAQAAAAAAhDVUMIU4VXuGOVTGhzlUVYc5VVWGOVXGhThVe4U1VTABAAAAAAABAAEAAACHOVRMAQABAAAAAAABAAEAAAEAAAEAAACFN1I4hjhUqgAAAAAAAAAAhjhUqoQ2UjgAAAAAAAAAAAEAAQAAAAAAAQAAAAEAAAAAAAAAAAABAAEBAAABAAAAgCtVBoc2URMBAAAAAAEAAIc2UROAKlUGAQABAAABAAAAAQAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAACAAAABAAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAhzxaEYA7ThqAO08ahTdZFwAAAAAAAAAAAAAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAhTdZF4A7ThqAO04ahzxaEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAACGOFSqhjlU/4Y5Vf+GOFXiAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGOFXihjlV/4Y5Vf+GOFSqAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAIY4VKqGOVX/hjlV/4Y4VOIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAIY4VeKGOVX/hjlV/4Y4VKoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAhjhUqoY5Vf+HOVX/hjhV4gAAAAABAAAAAAAAAAAAAQAAAAAAAQEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhjhV4oY5Vf+GOVT/hzhUqgAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAACGOFRMhjhVcoY4VXKEOFV1hzpWjIc6VoyHOlaMhztWjII2Vy8AAAAAAAAAAAAAAAAAAAEAgjZXL4Y6VoyHOlaMhzpWjIc6VoyFOVV1hjhVcoY4VXKGOVRMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAIA3UhyGOVX/hjlV/4Y5Vf+GOVX/hDZUVQAAAAAAAAAAAAABAAAAAACENlRVhjhV/4Y5Vf+GOVX/hjlV/4A3UhwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgDdSHIY5Vf+GOVT/hjlV/4Y5Vf+ENlRVAAAAAAAAAAAAAAAAAAAAAIQ2VFWGOVX/hzlU/4Y5Vf+HOVX/gDZSHAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAACAN1IchjlV/4Y5Vf+GOVX/hjlV/4Q2VFUAAQAAAAAAAAAAAAAAAAAAhDZUVYY5Vf+GOVX/hjlV/4Y5Vf+BN1IcAAAAAAAAAAAAAAAAAAAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAIc8WhGAOk4agDtOGoY3VTOGOVX/hzlV/4Y5Vf+GOVX/hDlVZoA7ThqAO04agDtOGoE7ThqEOVVmhjlV/4Y5Vf+GOVT/hjlV/4c3VTOAO04agDtOGoc8WhEAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAhjhUqoY5Vf+GOVX/hjlV/4Y5Vf+GOFX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+HOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlU/4Y5Vf+GOVX/hjlUqgABAAAAAAEAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAABAAAAAACGOFSqhjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjhV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4c5Vf+GOVX/hjlV/4Y5Vf+GOVWqAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQAAAIY5VKqGOFX/hjlV/4Y4Vf+GOVT/hjlU/4Y5Vf+HOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VP+HOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVT/hjlV/4Y4VKoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAhjhUqoY5VP+GOVX/hjlV/4c4Vf+GOVX/hjlV/4Y5Vf+GOVX/hzlV/4Y5Vf+GOVX/hzlU/4Y5Vf+GOVX/hjlV/4c5Vf+GOVX/hjlV/4Y5Vf+GOVT/hjhUqgAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAACGOFSqhjlV/4Y5Vf+GOFX/hjlU/4Y5VcaEN1NThDdTU4U3U1OGOFXZhjlV/4c5Vf+GOFXZhDdTU4Q3UlOEN1NThjlVxoY5Vf+GOVX/hjlV/4Y5Vf+GOFSqAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAIY4VKqGOVX/hjlV/4Y5VP+GOVX/hjhUqgAAAAAAAAAAAAAAAIY5VcaGOVX/hjlV/4Y5VMYAAAAAAAAAAAAAAQCGOFSqhjlV/4Y5Vf+GOVT/hjlV/4Y4VKoBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAACCN1UzhjlV5IY5VeSGOVXkhjlV9oY5Vf+GOVX/hjlV/4Y5Vf+GOVSqAAAAAAAAAAABAAAAhjlVxoc5Vf+GOVX/hjlUxgAAAAABAAAAAAABAIY4VKqGOVX/hzlV/4c5Vf+GOVX/hjhV9oY5VeSGOFXkhjhV5IU4VjIAAAAAgDtPGoU5U0eGOVXkhjlU5IY5VeSGOVX2hjlU/4Y5Vf+GOVX/hzlV/4c4VKoAAAAAAAAAAAEAAACGOVXGhjlV/4Y5Vf+GOVXGAQAAAAABAAABAAAAhjhUqoY5Vf+GOVX/hjlV/4Y5Vf+GOVX2hjlV5IY5VeSGOVXkhTlTR4A7ThqGOVX/hjlVxgAAAAAAAAAAAAAAAIY4VKqHOVX/hjhV/4Y5Vf+GOVX/hjhVqgAAAAAAAAAAAAAAAIY5VcaGOVX/hjlV/4Y5VcYAAAAAAAAAAAEAAACGOFSqhjlV/4Y5Vf+GOVX/hjhV/4Y4VKoAAAAAAAAAAAAAAACGOVXGhjlV/4Y5Vf+HOVXGAAEAAAAAAAAAAAAAhjhUqoY5Vf+HOVX/hjlV/4c5Vf+GOFSqAQAAAAAAAAAAAAAAhjlVxoY5Vf+GOFX/hjlVxgAAAAAAAAAAAAEAAIY4VKqHOFX/hzlV/4Y4Vf+GOFX/hjhUqgAAAAAAAAEAAAAAAIY5VcaHOVX/hjlV/4Y5VcYAAQAAAAAAAAEAAACGOFSqhjlV/4Y5Vf+GOVX/hjlV/4Y4VKoAAAAAAAAAAAAAAACGOVXGhjlV/4Y5Vf+GOVXGAAAAAAAAAAAAAAAAhjhUqoY5Vf+HOVX/hjlV/4Y5Vf+GOFSqAAEAAAAAAAAAAAAAhjlVxoY5Vf+GOVX/hjlVxgEAAAAAAAAAAAAAAIY4VKqGOVX/hjlV/4Y5Vf+GOVX/hjhV2Yc6VoyHOlaMhzpWjIc5VeWGOVX/hjlV/4Y5VeWHOlaMhztWjIc7VoyGOFXZhjlV/4Y5Vf+HOVX/hjlV/4Y4VaoAAAAAAAAAAAEAAACHOVXGhjlV/4Y5Vf+GOVXGAQABAAEAAAAAAQAAhjhUqoY5Vf+GOVX/hjlV/4Y5VP+GOVX/hjlV/4Y5Vf+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y5VP+GOVX/hjlV/4Y5Vf+GOFX/hjlV/4Y5Vf+GOVX/hjhUqgAAAAAAAAAAAQAAAIY5VcaGOVX/hjhV/4Y5VcYBAAAAAAAAAAAAAQCGOFSqhjhV/4Y5Vf+GOVX/hjlV/4Y5VP+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4c5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlU/4Y5Vf+GOVX/hjlU/4Y5Vf+GOVSqAAAAAAAAAAAAAAAAhjhVxoY5Vf+GOVX/hjlVxgAAAAAAAAAAAAAAAIc8WhGAO04ahzlV5YY4Vf+GOVX/hjlV/4Y5VP+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOFX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOFXlgDtOGoc8WhEAAAAAAAAAAAAAAACGOVXGhjlV/4Y5Vf+GOVXGAAAAAAABAQAAAAAAAAAAAAAAAACFOVTLhjlV54Y5VP+GOVT/hjlV/4Y4VP+GOVX/hjlV/4Y5Vf+GOVX/hjlU/4Y5Vf+GOVX/hjlV/4Y5Vf+GOFX/hjlV54Q4VMsBAAEAAAAAAAAAAAAAAAEAAAAAAIY5VcaGOVX/hjlV/4Y5VcYAAAAAAAABAAAAAAAAAQAAAAAAAAAAAACAN1IchjlV/4Y5Vf+GOVX/hjlV/4Y5VP+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+HOVX/hjlV/4Y5Vf+AN1IcAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAhjlVxoY5Vf+GOVWrhzhUhQABAAAAAAAAAAEAAAAAAAAAAAAAAAEAAIY2UROHOVWrhzlVq4Y4VdCGOVX/hThVx4c5VauGOVWrhjlVq4Y5VKuFOFXHhjlV/4Y4VdCGOVWrhjlVq4Y2URMAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAACGO1SFhjlVqwAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAhThTcYY5Vf+ENlRVAAAAAAAAAAAAAAAAAAAAAIQ3VFWHOVX/hThTcQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFOVNxhjlV/4Q2VFUAAAEAAAAAAAAAAAABAQAAhDZUVYY5Vf+FOFNxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAABAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAIU4U3GGOVX/hDZUVQEAAAAAAAAAAAAAAAABAACENlRVhjlV/4U4U3EAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAhTNSGYc2UTmGNlETAAAAAAAAAAAAAAAAAAAAAIY2UROGNlE5hTNSGQAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAADAAAABgAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAABgEBgCHE5VQlxOVUJcTlVCYBAYAiqVVUDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqVVUDgEBgCHE5VQlxOVUJcTlVCYBAYAj/AAABAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAQAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAACAMU4ahThUiIU5VZmFOVWZhTlVmYY5VZSEN1U8AAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAQCEN1U8hDlUlIU5VZmFOVWZhTlVmYY6VYmFM1IZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5VP+GOVX/hjlV/4Y5VfWGOVVjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAACGOVVjhjlV9YY5Vf+GOVX/hzlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5VfWGOVVjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQCGOVVjhjlV9YY5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hzlV/4Y5VfWGOVVjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGOVVjhjlV9YY5VP+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5VfWGOVVjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAACGOVVjhzlV9YY5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACHOFAghzpVqIY4Vb6GOFW+hjhVvoY5VbmGOVdwhzxYQIc8WECHPFhAhzxYQIc8WECEOFU2kklJBwAAAAAAAAAAAAAAAAAAAAAAAQAAAQAAAJJJSQeEOVU2hzxYQIc8WECHPFhAhzxYQIc8WECGOFVyhjlVuYY4Vb6GOFW+hjhVvoc6VaiMOlIfAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAI45VQmFOFSbhjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+HOVTUhDVPHQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAIQ1Tx2HOVTUhjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+FOFSbjjlVCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQAAAI45VQmFOFSbhjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+HOVTUhDVPHQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAIQ1Tx2HOVTUhjlV/4Y5Vf+GOFX/hjlV/4Y5Vf+FOFSbjjlVCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI45VQmFOFSbhjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+HOVTUhDVPHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQ1Tx2HOVTUhjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+FOFSbjzlVCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI45VQmFOFSbhjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+HOVTUhDVPHQAAAAAAAQAAAQAAAAAAAAAAAAAAAAAAAIQ1Tx2HOVTUhjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+FOFSbjjlVCQAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI45VQmFOFSbhjlV/4Y5VP+GOVX/hjlV/4Y5Vf+HOVTUhDVPHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQ1Tx2HOVTUhjlV/4Y5Vf+GOVX/hzlV/4Y5Vf+FOFSbjjlVCQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAABgUBgCHE5VQlxOVUJcTlVCYA5VRKFOFWfhjlV/4Y5Vf+GOFX/hjlV/4Y5Vf+FOFXWhzlVJHE5VQlxOVUJcTlVCXE5VAlxOFUJcTlVCYc5VSSFOFXWhzlV/4Y5Vf+GOVX/hzlV/4Y5Vf+FOFWfgDlVEnE5VAlxOVUJcTlVCYBAYAj/AAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAMU4ahThUiIU5VZmFOVWZhTlVmYc5VZ2GOVXXhjlV/4Y5Vf+GOVX/hzlV/4Y5Vf+GOVXuhTlVpYU5VZmFOVWZhTlVmYU5VZmFOVWZhDlVmYY5VaWGOVXuhjlV/4Y5VP+GOVX/hjlV/4Y5Vf+GOFXXhTlUnYU5VZmFOVWZhTlVmYY6VYmFM1IZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGN1UqhzhV4oY5VP+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VOKGN1UqAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5VP+GOFX/hjlV/4Y5Vf+GOFX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hzlV/4Y5Vf+GOFX/hzlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hzlV/4Y5VP+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VP+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VP+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOFX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hzlV/4Y5VP+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VP+GOFX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VPqFOVTahTlV04U5VdOFOVXThTlV04U5Ve+GOFX/hjlV/4Y5Vf+GOVX/hTlV74U5VdOFOVXThTlV04U5VdOFOVTahjlV+oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y5VeWDNlVCiTdSHIk3UhyJN1IciTdSHIY5VauGOVX/hjlV/4Y5Vf+GOVX/hjlVq4k3UhyJN1IciTdSHIk3UhyDNlVChjlV5YY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAQAAAAAAAAAAAIY5VaCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAQCGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAQAAAAAAAAAAAQAAAQAAAAAAAAAAAAAAAAAAgjdTJYY4UmWGOFNlhjhTZYY4U2WFOFR/hjlV7oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAQAAAAAAAIY5VKCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAACGN1UqhzhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hzlV/4Y5Ve6FOFR/hjhTZYY4UmWGOFNlhjhTZYo3WiUAAAAAAAAAAAAAAAAAAAAAhDhUW4Y5VfaGOFX2hjlV9oY5VfaGOVT4hjlV/oY5Vf+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf6GOVT4hjlV9oY5VfaGOVX2hjlV9oQ4VFsAAAAAAAAAAHE5VAlxOVUJhThVYIY5VfaGOVX2hjlV9oY5VfaGOVT4hjlV/oY5VP+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VOKGN1UqAQAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5VP+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOFX/hjlV/4Y5Vf6GOVT4hjlV9oY5VfaGOVX2hjlV9oU4VWBxOVUJcTlVCYU5VJmFOVWZhTlUhoY4U2WGOFNlhjhTZYY4U2WFOFR/hjlV7oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hzlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5VP+GOFX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VO6FOFR/hjhTZYY4U2WGOVNlhjhTZYU5VIaFOVWZhTlVmYY5Vf+GOVX/hzhUoAAAAQAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAIY5VaCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hzlV/4Y5VP+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5VP+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5Vf+GOFX/hjhUoAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5Vf+GOFX/hjhUoAAAAQAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGNlUqAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAQAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5VP+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VeqHOlVghzxYQIc8WECHPFhAhzxYQIY5VbiGOVX/hzlV/4Y5VP+GOVX/hjlVuIc8WECHPFhAhzxYQIc8WECGOlRhhjlV6oY5Vf+GOFX/hjlV/4Y5Vf+GOFX/hjlV/4Y4VeKGNlUqAQAAAAAAAAAAAAAAAQAAAIY5VKCGOVX/hjlV/4Y5VP+GOVX/hjhUoAAAAAAAAQAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOFX/hjlV/4Y5VP+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VP+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAQAAAAAAAIY5VKCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5VP+GOVX/hjhUoAAAAAAAAQAAAAAAAAAAAACGN1UqhjhV4oY5Vf+GOVX/hzlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VP+GOVX/hzlV/4Y5VP+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOFX/hzlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y4VeKGN1UqAAAAAAAAAAAAAAAAAQAAAIY5VKCGOVX/hjlV/4Y5Vf+GOFX/hzhUoAAAAAAAAAAAAAAAAAAAAACAMU4ahjpUiYU5VZmFOVXBhjlV+4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VP+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOFX/hjlV/4Y5VfuFOVXBhTlVmYU4VIiFM1IZAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAQAAAAAAAAD/AAABgEBgCHE5VQmHOFZohjlV9oY5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VfaHOFZocTlVCYBAYAj/AQABAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFOFVghTlV7YY5VfaGOVX7hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOFX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOFX/hjlV/4Y5Vf+GOVX8hjlV9oU5Ve2GOFZfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIY5VaCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDO1UnhjpUYYU5U2uFOFXDhjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+FOFXDhTlTa4Y6VGGDO1UnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5Vf+GOVX/hjhUoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI45VQmFOFSbhjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VP+GOVX/hjlV/4Y5Vf+GOVX/hjlV/4Y5VP+GOVX/hjlV/4Y5Vf+FOFSbjjlVCQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAIY5VKCGOVX/hjlV/4Y5VOOGOVXjhjlUjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBAYAiGOVSLhjlV44Y5VeOGOVXjhjlV+IY5VP+GOVX6hjlV5oY5VOOGOVXjhjlV44Y5VeOGOVXjhzlV44Y5VOaGOVX6hjlV/4Y5VfiGOVXjhjlV44Y5VeOFOVWKgEBgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAIY5VI+GOVXjhjlV44g1UyuINFMrgDdSHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAIAAAQKJO1gaiDVTK4g1UyuINVMrhzhVx4Y5Vf+FOVXchDlUQ4g1UyuINVMriDVTK4g1UyuINVMriDVTK4U5VUOFOVXchjlV/4Y4VciINVMriDVTK4g1UyuJO1gagAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA3UxyINFMriDVTKwAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhjlUvIY5Vf+HOVTUhDVPHQAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAIQ1Tx2HOVTUhjlV/4Y5VLwAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAhjlUvIY5Vf+HOVTUhDVPHQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAIQ1Tx2HOFTUhjlV/4Y5VLwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhjlUvIY5Vf+HOVTUhDVPHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQ1Tx2HOVTUhjlV/4Y5VLwAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhjlUvIY5Vf+HOVTUhDVPHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQ1Tx2HOVTUhjlV/4Y5VLwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhzdURoY4U1+INlRPiy5GCwAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAIsuRguIN1RPhjhTX4c3VEYAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
"""


class WebRequestHandler(BaseHTTPRequestHandler):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)

  def do_GET(self):
    self.send_response(200)

  def do_POST(self):
    try:
      content_length = int(self.headers["Content-Length"])
      post_data = self.rfile.read(content_length)

      print("Received POST data:", post_data)

    except Exception as e:
      pass


class WebServerThread(threading.Thread):
  def __init__(self):
    super().__init__(name="WebServerThread", daemon=True)
    self.host = config["http"]["HOST"]
    self.port = int(config["http"]["PORT"])

  def run(self):
    print(f"Starting web server on http://{self.host}:{self.port}")

    def handler(*args, **kwargs):
      WebRequestHandler(*args, **kwargs)

    server = HTTPServer((self.host, self.port), handler)

    try:
      server.serve_forever()
    except Exception as e:
      print(f"Web server error: {e}")
    finally:
      server.server_close()
      print("Web server stopped")


class USBMonitorThread(threading.Thread):
  def __init__(self):
    super().__init__(name="USBMonitorThread", daemon=True)

  def on_usb_connect(self, device_id, device_info, *args, **kwargs):
    with shared_data.lock:
      newDrives = detectNewUSBDrives(shared_data.data["all_drives"])

      if len(newDrives) > 0:
        shared_data.data["current_drive"] = newDrives[0]
        print(shared_data.data["current_drive"])

        if config["usb-monitor"]["enabled"].lower() == "true":
          print("works")

      shared_data.data["all_drives"] = listUSBDevices()

  def on_usb_disconnect(self, device_id, device_info, *args, **kwargs):
    with shared_data.lock:
      shared_data.data["all_drives"] = listUSBDevices()

  def run(self):
    try:
      monitor = USBMonitor()
      monitor.start_monitoring(on_connect=self.on_usb_connect,
                               on_disconnect=self.on_usb_disconnect,
                               check_every_seconds=int(config["usb-monitor"]["check_every_seconds"]))
    except Exception as e:
      print(f"USB monitor error: {e}")
      pass


class SysTrayThread(threading.Thread):
  def __init__(self):
    super().__init__(name="SysTrayThread", daemon=True)

  def create_image(self):
    icon_data = base64.b64decode(ICO_BASE)
    return Image.open(io.BytesIO(icon_data))

  def on_clicked(self, icon, item):
    if str(item) == "Exit":
      icon.stop()
      print("Force Exiting...")
      os._exit(0)

  def edit_conf(self, icon, item):
    if str(item) != "Edit Config":
      return

    try:
      config_path = "config.ini"
      initial_mtime = os.path.getmtime(config_path)

      process = subprocess.Popen(['notepad.exe', config_path])
      process.wait()

      final_mtime = os.path.getmtime(config_path)
      modified = final_mtime > initial_mtime

      if modified:
        print("Config modified, restarting service...")
        win32serviceutil.RestartService(config["general"]["SERVICE_NAME"])

    except Exception as e:
      print(f"Error editing config: {e}")

  def run(self):
    menu = (
        pystray.MenuItem("Edit Config", self.edit_conf),
        pystray.MenuItem("Restart", lambda icon, item: win32serviceutil.RestartService(
          config["general"]["SERVICE_NAME"])),
        pystray.MenuItem("Exit", self.on_clicked, visible=config["systray"]["enable_exit"].lower(
        ) == "true")
    )

    icon = pystray.Icon(
        config["systray"]["TRAY_NAME"],
        self.create_image(),
        config["systray"]["TRAY_TITLE"],
        menu
    )

    icon.run()


psCommand = """
Get-WmiObject Win32_DiskDrive | Where-Object { $_.InterfaceType -eq "USB" } | ForEach-Object {
    $drive = $_
    $partitions = Get-WmiObject -Query "ASSOCIATORS OF {Win32_DiskDrive.DeviceID='$($drive.DeviceID)'} WHERE AssocClass = Win32_DiskDriveToDiskPartition"
    $partitions | ForEach-Object {
        $partition = $_
        $logicalDisks = Get-WmiObject -Query "ASSOCIATORS OF {Win32_DiskPartition.DeviceID='$($partition.DeviceID)'} WHERE AssocClass = Win32_LogicalDiskToPartition"
        $logicalDisks | ForEach-Object {
            [PSCustomObject]@{
                DeviceID = $drive.DeviceID
                Caption = $drive.Caption
                Size = $drive.Size
                DriveLetter = $_.DeviceID
                VolumeName = $_.VolumeName
            }
        }
    }
} | ConvertTo-Json
"""


def listUSBDevices():
  process = subprocess.Popen(
      ["powershell", "-Command", psCommand],
      stdout=subprocess.PIPE,
      stderr=subprocess.PIPE,
      text=True
    )
  process.wait()

  stdout, stderr = process.communicate()

  try:
    out = json.loads(stdout)

    if isinstance(out, list):
      return out

    return [out]
  except Exception:
    return []


def detectNewUSBDrives(previousDrives):
  currentDrives = listUSBDevices()

  newDrives = [drive for drive in currentDrives if drive not in previousDrives]

  return newDrives


class SharedData:
  def __init__(self):
    self.lock = threading.Lock()
    self.data = {
        'all_drives': [],
        'current_drive': {},
    }


shared_data = SharedData()
shutdown_event = threading.Event()

if __name__ == "__main__":
  with shared_data.lock:
    shared_data.data["all_drives"] = listUSBDevices()

  config = configparser.ConfigParser()
  config.read("config.ini")

  web_server = WebServerThread()
  usb_monitor = USBMonitorThread()

  if config["systray"]["enabled"].lower() == "true":
    tray = SysTrayThread()
    tray.start()

  web_server.start()
  usb_monitor.start()

  try:
    while not shutdown_event.is_set():
      time.sleep(1)
  except KeyboardInterrupt:
    sys.exit(0)
